# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SVProgressHUD'
pod 'Alamofire'
pod 'JSONHelper'
pod 'SDWebImage'
pod 'DateTools'
pod 'Firebase'
pod 'ParseFacebookUtilsV4', '~> 1.8.5'
pod 'FBSDKCoreKit', '~> 4.6.0'
pod 'ParseUI', '~> 1.1.6'
pod 'Parse', '~> 1.8.5'
