# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'SVProgressHUD'
pod 'Alamofire'
pod 'JSONHelper'
pod 'SDWebImage'
pod 'DateTools'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Firebase'
